// src/components/dummyPublicTradeCards.js

export const dummyPublicTradeCards = [
  {
    color: '#D0E9BC',
    title: 'Consolidation Breakout',
    symbol: 'USD/CAD',
    change: '+50 pips',
    price1: '1.1000',
    price2: '1.1050',
    quantity: '2 lots',
    description: 'Entered after confirmation of breakout with strong volume...',
    time: '2 days ago',
    tags: ['#Breakout', '#MorningSession'],
    emoji: '😊',
    likes: 17,
    comments: 10,
    userId: 'User123',
    isPublic: true,
  },
  {
    color: '#B0DCF0',
    title: 'Swing Trade Success',
    symbol: 'EUR/USD',
    change: '+120 pips',
    price1: '1.2000',
    price2: '1.2120',
    quantity: '1 lot',
    description: 'I confidently entered a swing trade and held my position until my target was hit...',
    time: '3 days ago',
    tags: ['#SwingTrade', '#EveningSession'],
    emoji: '😎',
    likes: 23,
    comments: 8,
    userId: 'TraderJoe',
    isPublic: true,
  },
  {
    color: '#F5BCBB',
    title: 'Anxiety during FOMC',
    symbol: 'GBP/USD',
    change: '-20 pips',
    price1: '1.3800',
    price2: '1.3780',
    quantity: '2 lots',
    description: 'I was anxious during the FOMC meeting and exited the trade prematurely...',
    time: '5 days ago',
    tags: ['#FOMC', '#MorningSession'],
    emoji: '🤯',
    likes: 9,
    comments: 12,
    userId: 'ForexGuru',
    isPublic: true,
  },
  {
    color: '#C1BCBC',
    title: 'Frustrated Stop Loss Hit',
    symbol: 'AUD/USD',
    change: '-25 pips',
    price1: '0.7400',
    price2: '0.7375',
    quantity: '1.5 lots',
    description: 'Market moved against me and hit my stop loss. Felt frustrated...',
    time: '5 days ago',
    tags: ['#StopLoss', '#MorningSession'],
    emoji: '😠',
    likes: 12,
    comments: 4,
    userId: 'AngryTrader',
    isPublic: true,
  },
  {
    color: '#F5E0B2',
    title: 'Greedy for More Gains',
    symbol: 'TSLA',
    change: '-10%',
    price1: '$800',
    price2: '$720',
    quantity: '20 shares',
    description: 'Held the position too long, hoping for more gains. Lost profits...',
    time: '1 week ago',
    tags: ['#Greedy', '#EveningSession'],
    emoji: '🤑',
    likes: 18,
    comments: 7,
    userId: 'StockHawk',
    isPublic: true,
  },
  {
    color: '#D0E9BC',
    title: 'Steady Profits in Crypto',
    symbol: 'BTC/USD',
    change: '+500 USD',
    price1: '60000',
    price2: '60500',
    quantity: '0.5 BTC',
    description: 'Confidently entered a breakout trade and secured profit...',
    time: '2 days ago',
    tags: ['#Breakout', '#MorningSession'],
    emoji: '😎',
    likes: 25,
    comments: 15,
    userId: 'CryptoKing',
    isPublic: true,
  },
  {
    color: '#B0DCF0',
    title: 'Long-Term Investment',
    symbol: 'AAPL',
    change: '+5%',
    price1: '$150',
    price2: '$157.50',
    quantity: '50 shares',
    description: 'Held on to Apple stock for a steady gain over the quarter...',
    time: '1 week ago',
    tags: ['#LongTerm', '#Tech'],
    emoji: '😊',
    likes: 20,
    comments: 9,
    userId: 'InvestGuru',
    isPublic: true,
  },
  {
    color: '#F5BCBB',
    title: 'Nervous before Earnings',
    symbol: 'AMZN',
    change: '-2%',
    price1: '$3300',
    price2: '$3234',
    quantity: '10 shares',
    description: 'Exited before earnings call due to anxiety about market reaction...',
    time: '3 days ago',
    tags: ['#Earnings', '#Nervous'],
    emoji: '🤯',
    likes: 14,
    comments: 6,
    userId: 'MarketWatcher',
    isPublic: true,
  },
  {
    color: '#C1BCBC',
    title: 'Loss on Day Trade',
    symbol: 'SPY',
    change: '-0.5%',
    price1: '$450',
    price2: '$448',
    quantity: '100 shares',
    description: 'Tried to catch a quick gain but got stopped out...',
    time: '4 days ago',
    tags: ['#DayTrade', '#StopLoss'],
    emoji: '😠',
    likes: 11,
    comments: 5,
    userId: 'DayTraderPro',
    isPublic: true,
  },
  {
    color: '#F5E0B2',
    title: 'HODLing Strong',
    symbol: 'ETH/USD',
    change: '+200 USD',
    price1: '3200',
    price2: '3400',
    quantity: '2 ETH',
    description: 'Held through the dips and reaped the rewards...',
    time: '6 days ago',
    tags: ['#HODL', '#Crypto'],
    emoji: '🤑',
    likes: 28,
    comments: 12,
    userId: 'CryptoBeliever',
    isPublic: true,
  },
  {
    color: '#D0E9BC',
    title: 'Scalping Win',
    symbol: 'USD/JPY',
    change: '+30 pips',
    price1: '110.00',
    price2: '110.30',
    quantity: '1 lot',
    description: 'Quick scalp during the London session...',
    time: '8 hours ago',
    tags: ['#Scalping', '#Forex'],
    emoji: '😊',
    likes: 19,
    comments: 10,
    userId: 'ScalpMaster',
    isPublic: true,
  },
  {
    color: '#B0DCF0',
    title: 'Tech Sector Bounce',
    symbol: 'QQQ',
    change: '+3%',
    price1: '$370',
    price2: '$381.10',
    quantity: '30 shares',
    description: 'Rode the wave of the tech sector recovery...',
    time: '5 days ago',
    tags: ['#Tech', '#Recovery'],
    emoji: '😎',
    likes: 24,
    comments: 13,
    userId: 'TechTrader',
    isPublic: true,
  },
];
